Venu/arc ds pre release
Azure/azure-arc-validation pull request #68
Opened 2022-07-19 00:02 UTC by v-vgujjula

PRE-RELEASE feature integrated for both Direct and Indirect mode

2022-07-22 04:07 UTC, anraghun requested changes

2022-07-22 20:06 UTC, v-vgujjula commented on testsuite/running-tests.md
> +3. We have introduced `PRE-RELEASE` test feauture to provide an opportunity for customers and partners to provide pre-release feedback, pre-release versions of Azure Arc-enabled data services are mad
taken care

2022-07-22 20:07 UTC, v-vgujjula commented on testsuite/running-tests.md
> +4. We have introduced `PRE-RELEASE` test feauture to provide an opportunity for customers and partners to provide pre-release feedback, pre-release versions of Azure Arc-enabled data services are mad
taken care

2022-07-23 10:32 UTC, anraghun approved these changes

2022-07-23 10:32 UTC, merged